# This is a basic workflow to help you get started with Actions

name: Deployement

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTEHOST }}
        username: ${{ secrets.REMOTEUSER }}
        key: ${{ secrets.PRIVATEKEY  }}
        script: echo "test" >> test.txt
